name: .NET Core

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      redis:
        image: latest
        ports: 
        - "6379:6379"
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.0.100
    - name: Test with dotnet
      run: dotnet test
    - name: Build with dotnet
      run: dotnet build --configuration Release
    
